---
- name: NTP configuration
  host: RT_devices
  roles:
   - Juniper.junos
  connection: local
  gather_facts: no
  
  vars_login_prompt:
   - name: USERNAME
     prompt: Username
	 private: no
   - name: PASSWORD
     prompt: Password
	 private: yes
  
  tasks:
   - name: Load NTP server configuration
     juniper_junos_config:
	   user: "{{ USERNAME }}"
	   passwd: "{{ PASSWORD }}"
	   config_mode: exclusive
	   load: replace
	   lines:
	     - <configuration>
		 -    <system>
		 -      <ntp replace="replace">
		 -        <server>
		 -          <name>{{ ntp_server }}</name>
		 -        </server>
		 -      </ntp>
		 -    </system>
		 - </configuration>
	  format: xml
	  commit: true
     register: response